plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
    id 'org.gradle.test-retry' version '1.5.8'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.16.1'

    // Cucumber (Core + Java)
    implementation 'io.cucumber:cucumber-java:7.15.0'

    // Motor para conectar Cucumber con JUnit 5
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.15.0'

    // JUnit 5 (Plataforma y Suite para correr los tests)
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'

    implementation platform('io.qameta.allure:allure-bom:2.24.0')
    implementation 'io.qameta.allure:allure-cucumber7-jvm'
}

test {
    useJUnitPlatform()

    // Configuración para Allure
    systemProperty "cucumber.filter.tags", System.getProperty("cucumber.filter.tags")

    maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1

    // Reintentos
    retry {
        maxRetries = 2
        maxFailures = 10
        failOnPassedAfterRetry = false
    }
}

allure {
    version = '2.24.0'
}